<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Version>1.0.0</Version>
    <AssemblyName>SystemMetricsPlugin</AssemblyName>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Fennel" Version="0.3.0" />
    <PackageReference Include="Monq.Plugins.Abstractions" Version="3.0.0">
      <Private>false</Private>
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="System.IO.FileSystem.DriveInfo" Version="4.3.1" />
  </ItemGroup>
</Project>
