<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Version>1.0.0</Version>
    <AssemblyName>bufferedFileReaderPlugin</AssemblyName>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Monq.Plugins.Abstractions" Version="4.0.0-rev-36038457687">
      <Private>false</Private>
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
